schemaVersion: "1.0"
id: diamond-sutra
title: 金剛經解義
titleEn: Diamond Sutra Explained
tradition: Mahayana
translator: 六祖慧能
translatorAttribution: 唐六祖大鑒真空普覺禪師解義
source: CBETA, X0459
sourceAttribution: CBETA, X0459, no. 459 of the Zokuzōkyō
description: 六祖慧能大師對《金剛般若波羅蜜經》的註解，闡明「應無所住而生其心」的實相般若智慧。
chapters: 32
