schemaVersion: "1.0"
id: spiritual-study
title: 心靈書房
titleEn: Spiritual Study
tradition: Other
translator: 各方大德
translatorAttribution: 現代智慧
source: 現代心靈著作
sourceAttribution: 精選
description: 精選現代心靈成長與智慧書籍，如《我可能錯了》、《當富豪遇上僧侶》等，幫助在現代生活中安頓身心。
chapters: 3
