schemaVersion: "1.0"
id: buddhist-anthology
title: 佛學選輯
titleEn: Buddhist Anthology
tradition: Mahayana
translator: 選輯
translatorAttribution: 歷代大德
source: 佛教經典與公案
sourceAttribution: 多處出處
description: 精選佛教故事、觀念解釋與禪門公案，如放下屠刀、十牛圖、五明等。
chapters: 4
