schemaVersion: "1.0"
id: samyukta-agama
title: 雜阿含經
titleEn: Samyukta Agama
tradition: Early Buddhism
translator: 求那跋陀羅
translatorAttribution: 劉宋天竺三藏求那跋陀羅譯
source: 大正新修大藏經第2冊 No.99
sourceAttribution: Taishō Tripitaka, Vol. 2, No. 99
description: 雜阿含經為早期佛教根本經典之一，收錄佛陀及弟子們的教說，內容涵蓋蘊、處、界、緣起、聖諦等核心教義。
chapters: 49
startChapter: 559
defaultChapter: 576

chapterList:
  - 559
  - 560
  - 561
  - 562
  - 563
  - 564
  - 565
  - 566
  - 567
  - 568
  - 569
  - 570
  - 571
  - 572
  - 573
  - 574
  - 575
  - 576
  - 577
  - 578
  - 579
  - 580
  - 581
  - 582
  - 583
  - 584
  - 585
  - 586
  - 587
  - 588
  - 589
  - 590
  - 591
  - 592
  - 593
  - 594
  - 595
  - 596
  - 597
  - 598
  - 599
  - 600
  - 601
  - 602
  - 603
  - "604-1"
  - "604-2"
  - "604-3"
  - "604-4"
