schemaVersion: "1.0"
id: samyukta-agama
title: 雜阿含經
titleEn: Samyukta Agama
tradition: Early Buddhism
translator: 求那跋陀羅
translatorAttribution: 劉宋天竺三藏求那跋陀羅譯
source: 大正新修大藏經第2冊 No.99
sourceAttribution: Taishō Tripitaka, Vol. 2, No. 99
description: 雜阿含經為早期佛教根本經典之一，收錄佛陀及弟子們的教說，內容涵蓋蘊、處、界、緣起、聖諦等核心教義。
chapters: 45
startChapter: 559
defaultChapter: 576
