schemaVersion: "1.0"
id: samyukta-agama
title: 雜阿含經
titleEn: Samyukta Agama
tradition: Early Buddhism
translator: 求那跋陀羅
translatorAttribution: 劉宋天竺三藏求那跋陀羅譯
source: 大正新修大藏經第2冊 No.99
sourceAttribution: Taishō Tripitaka, Vol. 2, No. 99
description: 雜阿含經為早期佛教根本經典之一，與巴利語《相應部》對應，收錄佛陀及弟子們的教說，按主題分類編排，內容涵蓋蘊、處、界、緣起、聖諦等核心教義，為南傳與北傳佛教共同依據的重要經典。本站目前收錄卷二十一（第559-575經，共17經）、卷二十二（第576-603經，共28經）。
chapters: 45
startChapter: 559
defaultChapter: 576
